project_id = "schegpkwfwkgfmmpnzic"

[functions.gold-sniper-engine]
verify_jwt = false

[functions.get-live-price]
verify_jwt = false

[functions.dashboard]
verify_jwt = false

[functions.send-daily-report]
verify_jwt = false

[functions.backup-to-drive]
verify_jwt = false

[functions.ai-candle-scanner]
verify_jwt = false

[functions.update-prev-close]
verify_jwt = false
